// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/shuoyang2016/mywish/rpc/money.proto

/*
Package rpc is a generated protocol buffer package.

It is generated from these files:
	github.com/shuoyang2016/mywish/rpc/money.proto
	github.com/shuoyang2016/mywish/rpc/mywish_service.proto
	github.com/shuoyang2016/mywish/rpc/player.proto
	github.com/shuoyang2016/mywish/rpc/product.proto

It has these top-level messages:
	Price
	Bid
	GetProductRequest
	GetProductResponse
	BidProductRequest
	BidProductResponse
	PayOffRequest
	PayOffResponse
	CreateProductRequest
	CreateProductResponse
	CloseProductRequest
	CloseProductResponse
	GetProductsRequest
	GetProductsResponse
	UpdateProductRequest
	UpdateProductResponse
	CheckOrCreateUserRequest
	CheckOrCreateUserResponse
	AuthUserRequest
	AuthUserResponse
	UpdateUserRequest
	UpdateUserResponse
	DeleteUserRequest
	DeleteUserResponse
	GetUserRequest
	GetUserResponse
	CreateUserRequest
	CreateUserResponse
	CreateBidderRequest
	CreateBidderResponse
	GetBidderRequest
	GetBidderResponse
	UpdateBidderRequest
	UpdateBidderResponse
	TestingDropRequest
	TestingDropResponse
	BuyProductRequest
	BuyProductResponse
	Bidder
	Product
	KVPair
	SupriseProduct
	VagueProduct
*/
package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CurrencyType int32

const (
	CurrencyType_DOLLAR CurrencyType = 0
	CurrencyType_RMB    CurrencyType = 1
)

var CurrencyType_name = map[int32]string{
	0: "DOLLAR",
	1: "RMB",
}
var CurrencyType_value = map[string]int32{
	"DOLLAR": 0,
	"RMB":    1,
}

func (x CurrencyType) String() string {
	return proto.EnumName(CurrencyType_name, int32(x))
}
func (CurrencyType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Price struct {
	CurrencyType CurrencyType `protobuf:"varint,1,opt,name=currency_type,json=currencyType,enum=rpc.CurrencyType" json:"currency_type,omitempty"`
	Amount       float64      `protobuf:"fixed64,2,opt,name=amount" json:"amount,omitempty"`
}

func (m *Price) Reset()                    { *m = Price{} }
func (m *Price) String() string            { return proto.CompactTextString(m) }
func (*Price) ProtoMessage()               {}
func (*Price) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Price) GetCurrencyType() CurrencyType {
	if m != nil {
		return m.CurrencyType
	}
	return CurrencyType_DOLLAR
}

func (m *Price) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type Bid struct {
	Id        int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	BidderId  int64  `protobuf:"varint,2,opt,name=bidder_id,json=bidderId" json:"bidder_id,omitempty"`
	BuyerId   int64  `protobuf:"varint,3,opt,name=buyer_id,json=buyerId" json:"buyer_id,omitempty"`
	ProductId int64  `protobuf:"varint,4,opt,name=product_id,json=productId" json:"product_id,omitempty"`
	Price     *Price `protobuf:"bytes,5,opt,name=price" json:"price,omitempty"`
}

func (m *Bid) Reset()                    { *m = Bid{} }
func (m *Bid) String() string            { return proto.CompactTextString(m) }
func (*Bid) ProtoMessage()               {}
func (*Bid) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Bid) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Bid) GetBidderId() int64 {
	if m != nil {
		return m.BidderId
	}
	return 0
}

func (m *Bid) GetBuyerId() int64 {
	if m != nil {
		return m.BuyerId
	}
	return 0
}

func (m *Bid) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *Bid) GetPrice() *Price {
	if m != nil {
		return m.Price
	}
	return nil
}

func init() {
	proto.RegisterType((*Price)(nil), "rpc.Price")
	proto.RegisterType((*Bid)(nil), "rpc.Bid")
	proto.RegisterEnum("rpc.CurrencyType", CurrencyType_name, CurrencyType_value)
}

func init() { proto.RegisterFile("github.com/shuoyang2016/mywish/rpc/money.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 287 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x4d, 0x4b, 0x03, 0x31,
	0x10, 0x86, 0x4d, 0x63, 0xbf, 0xc6, 0x5a, 0x6a, 0x0e, 0x52, 0xbf, 0x60, 0xa9, 0x97, 0xe2, 0x61,
	0xa3, 0x15, 0x7a, 0xb7, 0x7a, 0x29, 0x54, 0x94, 0x20, 0x78, 0x2c, 0xbb, 0x49, 0xd8, 0x06, 0xdc,
	0x24, 0xa4, 0x09, 0x92, 0x3f, 0xe1, 0x6f, 0x96, 0x66, 0xf7, 0xd0, 0xe3, 0xfb, 0x3e, 0xc9, 0x30,
	0xcf, 0x40, 0x5e, 0x29, 0xbf, 0x0b, 0x65, 0xce, 0x4d, 0x4d, 0xf7, 0xbb, 0x60, 0x62, 0xa1, 0xab,
	0xc5, 0xe3, 0xd3, 0x92, 0xd6, 0xf1, 0x57, 0xed, 0x77, 0xd4, 0x59, 0x4e, 0x6b, 0xa3, 0x65, 0xcc,
	0xad, 0x33, 0xde, 0x10, 0xec, 0x2c, 0xbf, 0xbe, 0xad, 0x8c, 0xa9, 0x7e, 0x24, 0x2d, 0xac, 0xa2,
	0x85, 0xd6, 0xc6, 0x17, 0x5e, 0x19, 0xbd, 0x6f, 0x9e, 0xcc, 0xbe, 0xa1, 0xfb, 0xe9, 0x14, 0x97,
	0x64, 0x09, 0xe7, 0x3c, 0x38, 0x27, 0x35, 0x8f, 0x5b, 0x1f, 0xad, 0x9c, 0xa2, 0x0c, 0xcd, 0xc7,
	0x8b, 0x8b, 0xdc, 0x59, 0x9e, 0xbf, 0xb6, 0xe4, 0x2b, 0x5a, 0xc9, 0x46, 0xfc, 0x28, 0x91, 0x4b,
	0xe8, 0x15, 0xb5, 0x09, 0xda, 0x4f, 0x3b, 0x19, 0x9a, 0x23, 0xd6, 0xa6, 0xd9, 0x1f, 0x02, 0xbc,
	0x52, 0x82, 0x8c, 0xa1, 0xa3, 0x44, 0x1a, 0x86, 0x59, 0x47, 0x09, 0x72, 0x03, 0xc3, 0x52, 0x09,
	0x21, 0xdd, 0x56, 0x89, 0xf4, 0x05, 0xb3, 0x41, 0x53, 0xac, 0x05, 0xb9, 0x82, 0x41, 0x19, 0x62,
	0xc3, 0x70, 0x62, 0xfd, 0x94, 0xd7, 0x82, 0xdc, 0x01, 0x58, 0x67, 0x44, 0xe0, 0xfe, 0x00, 0x4f,
	0x13, 0x1c, 0xb6, 0xcd, 0x5a, 0x90, 0x0c, 0xba, 0xf6, 0xe0, 0x31, 0xed, 0x66, 0x68, 0x7e, 0xb6,
	0x80, 0xb4, 0x76, 0x32, 0x63, 0x0d, 0x78, 0xb8, 0x87, 0xd1, 0xb1, 0x06, 0x01, 0xe8, 0xbd, 0x7d,
	0x6c, 0x36, 0x2f, 0x6c, 0x72, 0x42, 0xfa, 0x80, 0xd9, 0xfb, 0x6a, 0x82, 0xca, 0x5e, 0xba, 0xca,
	0xf3, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb7, 0x00, 0x10, 0x93, 0x6a, 0x01, 0x00, 0x00,
}
