// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/shuoyang2016/mywish/rpc/mywish_service.proto

package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Error int32

const (
	Error_SUCCESS         Error = 0
	Error_GENERIC_FAILURE Error = 1
)

var Error_name = map[int32]string{
	0: "SUCCESS",
	1: "GENERIC_FAILURE",
}
var Error_value = map[string]int32{
	"SUCCESS":         0,
	"GENERIC_FAILURE": 1,
}

func (x Error) String() string {
	return proto.EnumName(Error_name, int32(x))
}
func (Error) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type GetProductRequest struct {
	ProductId   int64  `protobuf:"varint,1,opt,name=product_id,json=productId" json:"product_id,omitempty"`
	ProductName string `protobuf:"bytes,2,opt,name=product_name,json=productName" json:"product_name,omitempty"`
}

func (m *GetProductRequest) Reset()                    { *m = GetProductRequest{} }
func (m *GetProductRequest) String() string            { return proto.CompactTextString(m) }
func (*GetProductRequest) ProtoMessage()               {}
func (*GetProductRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *GetProductRequest) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *GetProductRequest) GetProductName() string {
	if m != nil {
		return m.ProductName
	}
	return ""
}

type GetProductResponse struct {
	Product *Product `protobuf:"bytes,1,opt,name=product" json:"product,omitempty"`
}

func (m *GetProductResponse) Reset()                    { *m = GetProductResponse{} }
func (m *GetProductResponse) String() string            { return proto.CompactTextString(m) }
func (*GetProductResponse) ProtoMessage()               {}
func (*GetProductResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *GetProductResponse) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type BidProductRequest struct {
	Bid *Bid `protobuf:"bytes,1,opt,name=bid" json:"bid,omitempty"`
}

func (m *BidProductRequest) Reset()                    { *m = BidProductRequest{} }
func (m *BidProductRequest) String() string            { return proto.CompactTextString(m) }
func (*BidProductRequest) ProtoMessage()               {}
func (*BidProductRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *BidProductRequest) GetBid() *Bid {
	if m != nil {
		return m.Bid
	}
	return nil
}

type BidProductResponse struct {
	Error Error `protobuf:"varint,1,opt,name=error,enum=rpc.Error" json:"error,omitempty"`
}

func (m *BidProductResponse) Reset()                    { *m = BidProductResponse{} }
func (m *BidProductResponse) String() string            { return proto.CompactTextString(m) }
func (*BidProductResponse) ProtoMessage()               {}
func (*BidProductResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *BidProductResponse) GetError() Error {
	if m != nil {
		return m.Error
	}
	return Error_SUCCESS
}

type BuyOutRequest struct {
}

func (m *BuyOutRequest) Reset()                    { *m = BuyOutRequest{} }
func (m *BuyOutRequest) String() string            { return proto.CompactTextString(m) }
func (*BuyOutRequest) ProtoMessage()               {}
func (*BuyOutRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

type BuyOutResponse struct {
}

func (m *BuyOutResponse) Reset()                    { *m = BuyOutResponse{} }
func (m *BuyOutResponse) String() string            { return proto.CompactTextString(m) }
func (*BuyOutResponse) ProtoMessage()               {}
func (*BuyOutResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

type CreateProductRequest struct {
	NewProduct *Product `protobuf:"bytes,1,opt,name=new_product,json=newProduct" json:"new_product,omitempty"`
	UserId     int64    `protobuf:"varint,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *CreateProductRequest) Reset()                    { *m = CreateProductRequest{} }
func (m *CreateProductRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateProductRequest) ProtoMessage()               {}
func (*CreateProductRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *CreateProductRequest) GetNewProduct() *Product {
	if m != nil {
		return m.NewProduct
	}
	return nil
}

func (m *CreateProductRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type CreateProductResponse struct {
	Status Error  `protobuf:"varint,1,opt,name=status,enum=rpc.Error" json:"status,omitempty"`
	Msg    string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
}

func (m *CreateProductResponse) Reset()                    { *m = CreateProductResponse{} }
func (m *CreateProductResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateProductResponse) ProtoMessage()               {}
func (*CreateProductResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *CreateProductResponse) GetStatus() Error {
	if m != nil {
		return m.Status
	}
	return Error_SUCCESS
}

func (m *CreateProductResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type GetProductsRequest struct {
	ProductId int64 `protobuf:"varint,1,opt,name=product_id,json=productId" json:"product_id,omitempty"`
}

func (m *GetProductsRequest) Reset()                    { *m = GetProductsRequest{} }
func (m *GetProductsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetProductsRequest) ProtoMessage()               {}
func (*GetProductsRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *GetProductsRequest) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

type GetProductsResponse struct {
	Product *Product `protobuf:"bytes,1,opt,name=product" json:"product,omitempty"`
}

func (m *GetProductsResponse) Reset()                    { *m = GetProductsResponse{} }
func (m *GetProductsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetProductsResponse) ProtoMessage()               {}
func (*GetProductsResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *GetProductsResponse) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type UpdateProductRequest struct {
	ProductId     int64  `protobuf:"varint,1,opt,name=product_id,json=productId" json:"product_id,omitempty"`
	RequestUserId int64  `protobuf:"varint,2,opt,name=request_user_id,json=requestUserId" json:"request_user_id,omitempty"`
	Price         *Price `protobuf:"bytes,3,opt,name=price" json:"price,omitempty"`
	IsDealPrice   bool   `protobuf:"varint,4,opt,name=is_deal_price,json=isDealPrice" json:"is_deal_price,omitempty"`
	BidId         int64  `protobuf:"varint,5,opt,name=bid_id,json=bidId" json:"bid_id,omitempty"`
}

func (m *UpdateProductRequest) Reset()                    { *m = UpdateProductRequest{} }
func (m *UpdateProductRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateProductRequest) ProtoMessage()               {}
func (*UpdateProductRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

func (m *UpdateProductRequest) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *UpdateProductRequest) GetRequestUserId() int64 {
	if m != nil {
		return m.RequestUserId
	}
	return 0
}

func (m *UpdateProductRequest) GetPrice() *Price {
	if m != nil {
		return m.Price
	}
	return nil
}

func (m *UpdateProductRequest) GetIsDealPrice() bool {
	if m != nil {
		return m.IsDealPrice
	}
	return false
}

func (m *UpdateProductRequest) GetBidId() int64 {
	if m != nil {
		return m.BidId
	}
	return 0
}

type UpdateProductResponse struct {
	ProductId int64 `protobuf:"varint,1,opt,name=product_id,json=productId" json:"product_id,omitempty"`
	DealId    int64 `protobuf:"varint,2,opt,name=deal_id,json=dealId" json:"deal_id,omitempty"`
}

func (m *UpdateProductResponse) Reset()                    { *m = UpdateProductResponse{} }
func (m *UpdateProductResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateProductResponse) ProtoMessage()               {}
func (*UpdateProductResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

func (m *UpdateProductResponse) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *UpdateProductResponse) GetDealId() int64 {
	if m != nil {
		return m.DealId
	}
	return 0
}

type CheckOrCreateUserRequest struct {
	UserName string `protobuf:"bytes,1,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
}

func (m *CheckOrCreateUserRequest) Reset()                    { *m = CheckOrCreateUserRequest{} }
func (m *CheckOrCreateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*CheckOrCreateUserRequest) ProtoMessage()               {}
func (*CheckOrCreateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

func (m *CheckOrCreateUserRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *CheckOrCreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CheckOrCreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CheckOrCreateUserResponse struct {
	Succeed bool   `protobuf:"varint,1,opt,name=succeed" json:"succeed,omitempty"`
	Details string `protobuf:"bytes,2,opt,name=details" json:"details,omitempty"`
}

func (m *CheckOrCreateUserResponse) Reset()                    { *m = CheckOrCreateUserResponse{} }
func (m *CheckOrCreateUserResponse) String() string            { return proto.CompactTextString(m) }
func (*CheckOrCreateUserResponse) ProtoMessage()               {}
func (*CheckOrCreateUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

func (m *CheckOrCreateUserResponse) GetSucceed() bool {
	if m != nil {
		return m.Succeed
	}
	return false
}

func (m *CheckOrCreateUserResponse) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

type AuthUserRequest struct {
}

func (m *AuthUserRequest) Reset()                    { *m = AuthUserRequest{} }
func (m *AuthUserRequest) String() string            { return proto.CompactTextString(m) }
func (*AuthUserRequest) ProtoMessage()               {}
func (*AuthUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{14} }

type AuthUserResponse struct {
}

func (m *AuthUserResponse) Reset()                    { *m = AuthUserResponse{} }
func (m *AuthUserResponse) String() string            { return proto.CompactTextString(m) }
func (*AuthUserResponse) ProtoMessage()               {}
func (*AuthUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{15} }

type UpdateUserRequest struct {
}

func (m *UpdateUserRequest) Reset()                    { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()               {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{16} }

type UpdateUserResponse struct {
}

func (m *UpdateUserResponse) Reset()                    { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()               {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{17} }

type DeleteUserRequest struct {
}

func (m *DeleteUserRequest) Reset()                    { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()               {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{18} }

type DeleteUserResponse struct {
}

func (m *DeleteUserResponse) Reset()                    { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()               {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{19} }

type GetUserRequest struct {
}

func (m *GetUserRequest) Reset()                    { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()               {}
func (*GetUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{20} }

type GetUserResponse struct {
}

func (m *GetUserResponse) Reset()                    { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string            { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()               {}
func (*GetUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{21} }

type CreateUserRequest struct {
}

func (m *CreateUserRequest) Reset()                    { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()               {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{22} }

type CreateUserResponse struct {
}

func (m *CreateUserResponse) Reset()                    { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()               {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{23} }

type CreateBidderRequest struct {
	BidderId   int64  `protobuf:"varint,1,opt,name=bidder_id,json=bidderId" json:"bidder_id,omitempty"`
	BidderName string `protobuf:"bytes,2,opt,name=bidder_name,json=bidderName" json:"bidder_name,omitempty"`
}

func (m *CreateBidderRequest) Reset()                    { *m = CreateBidderRequest{} }
func (m *CreateBidderRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateBidderRequest) ProtoMessage()               {}
func (*CreateBidderRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{24} }

func (m *CreateBidderRequest) GetBidderId() int64 {
	if m != nil {
		return m.BidderId
	}
	return 0
}

func (m *CreateBidderRequest) GetBidderName() string {
	if m != nil {
		return m.BidderName
	}
	return ""
}

type CreateBidderResponse struct {
}

func (m *CreateBidderResponse) Reset()                    { *m = CreateBidderResponse{} }
func (m *CreateBidderResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateBidderResponse) ProtoMessage()               {}
func (*CreateBidderResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{25} }

type GetBidderRequest struct {
	BidderId int64 `protobuf:"varint,1,opt,name=bidder_id,json=bidderId" json:"bidder_id,omitempty"`
}

func (m *GetBidderRequest) Reset()                    { *m = GetBidderRequest{} }
func (m *GetBidderRequest) String() string            { return proto.CompactTextString(m) }
func (*GetBidderRequest) ProtoMessage()               {}
func (*GetBidderRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{26} }

func (m *GetBidderRequest) GetBidderId() int64 {
	if m != nil {
		return m.BidderId
	}
	return 0
}

type GetBidderResponse struct {
}

func (m *GetBidderResponse) Reset()                    { *m = GetBidderResponse{} }
func (m *GetBidderResponse) String() string            { return proto.CompactTextString(m) }
func (*GetBidderResponse) ProtoMessage()               {}
func (*GetBidderResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{27} }

type UpdateBidderRequest struct {
}

func (m *UpdateBidderRequest) Reset()                    { *m = UpdateBidderRequest{} }
func (m *UpdateBidderRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateBidderRequest) ProtoMessage()               {}
func (*UpdateBidderRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{28} }

type UpdateBidderResponse struct {
}

func (m *UpdateBidderResponse) Reset()                    { *m = UpdateBidderResponse{} }
func (m *UpdateBidderResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateBidderResponse) ProtoMessage()               {}
func (*UpdateBidderResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{29} }

func init() {
	proto.RegisterType((*GetProductRequest)(nil), "rpc.GetProductRequest")
	proto.RegisterType((*GetProductResponse)(nil), "rpc.GetProductResponse")
	proto.RegisterType((*BidProductRequest)(nil), "rpc.BidProductRequest")
	proto.RegisterType((*BidProductResponse)(nil), "rpc.BidProductResponse")
	proto.RegisterType((*BuyOutRequest)(nil), "rpc.BuyOutRequest")
	proto.RegisterType((*BuyOutResponse)(nil), "rpc.BuyOutResponse")
	proto.RegisterType((*CreateProductRequest)(nil), "rpc.CreateProductRequest")
	proto.RegisterType((*CreateProductResponse)(nil), "rpc.CreateProductResponse")
	proto.RegisterType((*GetProductsRequest)(nil), "rpc.GetProductsRequest")
	proto.RegisterType((*GetProductsResponse)(nil), "rpc.GetProductsResponse")
	proto.RegisterType((*UpdateProductRequest)(nil), "rpc.UpdateProductRequest")
	proto.RegisterType((*UpdateProductResponse)(nil), "rpc.UpdateProductResponse")
	proto.RegisterType((*CheckOrCreateUserRequest)(nil), "rpc.CheckOrCreateUserRequest")
	proto.RegisterType((*CheckOrCreateUserResponse)(nil), "rpc.CheckOrCreateUserResponse")
	proto.RegisterType((*AuthUserRequest)(nil), "rpc.AuthUserRequest")
	proto.RegisterType((*AuthUserResponse)(nil), "rpc.AuthUserResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "rpc.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "rpc.UpdateUserResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "rpc.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "rpc.DeleteUserResponse")
	proto.RegisterType((*GetUserRequest)(nil), "rpc.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "rpc.GetUserResponse")
	proto.RegisterType((*CreateUserRequest)(nil), "rpc.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "rpc.CreateUserResponse")
	proto.RegisterType((*CreateBidderRequest)(nil), "rpc.CreateBidderRequest")
	proto.RegisterType((*CreateBidderResponse)(nil), "rpc.CreateBidderResponse")
	proto.RegisterType((*GetBidderRequest)(nil), "rpc.GetBidderRequest")
	proto.RegisterType((*GetBidderResponse)(nil), "rpc.GetBidderResponse")
	proto.RegisterType((*UpdateBidderRequest)(nil), "rpc.UpdateBidderRequest")
	proto.RegisterType((*UpdateBidderResponse)(nil), "rpc.UpdateBidderResponse")
	proto.RegisterEnum("rpc.Error", Error_name, Error_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for MyWishService service

type MyWishServiceClient interface {
	// <-------- Product APIs begin ---------> //
	CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductResponse, error)
	UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*UpdateProductResponse, error)
	GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error)
	GetProducts(ctx context.Context, in *GetProductsRequest, opts ...grpc.CallOption) (*GetProductsResponse, error)
	BidProduct(ctx context.Context, in *BidProductRequest, opts ...grpc.CallOption) (*BidProductResponse, error)
	// <-------- Product APIs end -----------> //
	// <-------- User APIs begin ---------> //
	CreateBidder(ctx context.Context, in *CreateBidderRequest, opts ...grpc.CallOption) (*CreateBidderResponse, error)
	GetBidder(ctx context.Context, in *GetBidderRequest, opts ...grpc.CallOption) (*GetBidderResponse, error)
	UpdateBidder(ctx context.Context, in *UpdateBidderRequest, opts ...grpc.CallOption) (*UpdateBidderResponse, error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	CheckOrCreateUser(ctx context.Context, in *CheckOrCreateUserRequest, opts ...grpc.CallOption) (*CheckOrCreateUserResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	AuthUser(ctx context.Context, in *AuthUserRequest, opts ...grpc.CallOption) (*AuthUserResponse, error)
}

type myWishServiceClient struct {
	cc *grpc.ClientConn
}

func NewMyWishServiceClient(cc *grpc.ClientConn) MyWishServiceClient {
	return &myWishServiceClient{cc}
}

func (c *myWishServiceClient) CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductResponse, error) {
	out := new(CreateProductResponse)
	err := grpc.Invoke(ctx, "/rpc.MyWishService/CreateProduct", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myWishServiceClient) UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*UpdateProductResponse, error) {
	out := new(UpdateProductResponse)
	err := grpc.Invoke(ctx, "/rpc.MyWishService/UpdateProduct", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myWishServiceClient) GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error) {
	out := new(GetProductResponse)
	err := grpc.Invoke(ctx, "/rpc.MyWishService/GetProduct", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myWishServiceClient) GetProducts(ctx context.Context, in *GetProductsRequest, opts ...grpc.CallOption) (*GetProductsResponse, error) {
	out := new(GetProductsResponse)
	err := grpc.Invoke(ctx, "/rpc.MyWishService/GetProducts", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myWishServiceClient) BidProduct(ctx context.Context, in *BidProductRequest, opts ...grpc.CallOption) (*BidProductResponse, error) {
	out := new(BidProductResponse)
	err := grpc.Invoke(ctx, "/rpc.MyWishService/BidProduct", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myWishServiceClient) CreateBidder(ctx context.Context, in *CreateBidderRequest, opts ...grpc.CallOption) (*CreateBidderResponse, error) {
	out := new(CreateBidderResponse)
	err := grpc.Invoke(ctx, "/rpc.MyWishService/CreateBidder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myWishServiceClient) GetBidder(ctx context.Context, in *GetBidderRequest, opts ...grpc.CallOption) (*GetBidderResponse, error) {
	out := new(GetBidderResponse)
	err := grpc.Invoke(ctx, "/rpc.MyWishService/GetBidder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myWishServiceClient) UpdateBidder(ctx context.Context, in *UpdateBidderRequest, opts ...grpc.CallOption) (*UpdateBidderResponse, error) {
	out := new(UpdateBidderResponse)
	err := grpc.Invoke(ctx, "/rpc.MyWishService/UpdateBidder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myWishServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := grpc.Invoke(ctx, "/rpc.MyWishService/CreateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myWishServiceClient) CheckOrCreateUser(ctx context.Context, in *CheckOrCreateUserRequest, opts ...grpc.CallOption) (*CheckOrCreateUserResponse, error) {
	out := new(CheckOrCreateUserResponse)
	err := grpc.Invoke(ctx, "/rpc.MyWishService/CheckOrCreateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myWishServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := grpc.Invoke(ctx, "/rpc.MyWishService/GetUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myWishServiceClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	out := new(DeleteUserResponse)
	err := grpc.Invoke(ctx, "/rpc.MyWishService/DeleteUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myWishServiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	out := new(UpdateUserResponse)
	err := grpc.Invoke(ctx, "/rpc.MyWishService/UpdateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myWishServiceClient) AuthUser(ctx context.Context, in *AuthUserRequest, opts ...grpc.CallOption) (*AuthUserResponse, error) {
	out := new(AuthUserResponse)
	err := grpc.Invoke(ctx, "/rpc.MyWishService/AuthUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MyWishService service

type MyWishServiceServer interface {
	// <-------- Product APIs begin ---------> //
	CreateProduct(context.Context, *CreateProductRequest) (*CreateProductResponse, error)
	UpdateProduct(context.Context, *UpdateProductRequest) (*UpdateProductResponse, error)
	GetProduct(context.Context, *GetProductRequest) (*GetProductResponse, error)
	GetProducts(context.Context, *GetProductsRequest) (*GetProductsResponse, error)
	BidProduct(context.Context, *BidProductRequest) (*BidProductResponse, error)
	// <-------- Product APIs end -----------> //
	// <-------- User APIs begin ---------> //
	CreateBidder(context.Context, *CreateBidderRequest) (*CreateBidderResponse, error)
	GetBidder(context.Context, *GetBidderRequest) (*GetBidderResponse, error)
	UpdateBidder(context.Context, *UpdateBidderRequest) (*UpdateBidderResponse, error)
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	CheckOrCreateUser(context.Context, *CheckOrCreateUserRequest) (*CheckOrCreateUserResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	AuthUser(context.Context, *AuthUserRequest) (*AuthUserResponse, error)
}

func RegisterMyWishServiceServer(s *grpc.Server, srv MyWishServiceServer) {
	s.RegisterService(&_MyWishService_serviceDesc, srv)
}

func _MyWishService_CreateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyWishServiceServer).CreateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.MyWishService/CreateProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyWishServiceServer).CreateProduct(ctx, req.(*CreateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyWishService_UpdateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyWishServiceServer).UpdateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.MyWishService/UpdateProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyWishServiceServer).UpdateProduct(ctx, req.(*UpdateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyWishService_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyWishServiceServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.MyWishService/GetProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyWishServiceServer).GetProduct(ctx, req.(*GetProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyWishService_GetProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyWishServiceServer).GetProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.MyWishService/GetProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyWishServiceServer).GetProducts(ctx, req.(*GetProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyWishService_BidProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BidProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyWishServiceServer).BidProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.MyWishService/BidProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyWishServiceServer).BidProduct(ctx, req.(*BidProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyWishService_CreateBidder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBidderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyWishServiceServer).CreateBidder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.MyWishService/CreateBidder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyWishServiceServer).CreateBidder(ctx, req.(*CreateBidderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyWishService_GetBidder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBidderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyWishServiceServer).GetBidder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.MyWishService/GetBidder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyWishServiceServer).GetBidder(ctx, req.(*GetBidderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyWishService_UpdateBidder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBidderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyWishServiceServer).UpdateBidder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.MyWishService/UpdateBidder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyWishServiceServer).UpdateBidder(ctx, req.(*UpdateBidderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyWishService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyWishServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.MyWishService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyWishServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyWishService_CheckOrCreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckOrCreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyWishServiceServer).CheckOrCreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.MyWishService/CheckOrCreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyWishServiceServer).CheckOrCreateUser(ctx, req.(*CheckOrCreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyWishService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyWishServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.MyWishService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyWishServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyWishService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyWishServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.MyWishService/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyWishServiceServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyWishService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyWishServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.MyWishService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyWishServiceServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyWishService_AuthUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyWishServiceServer).AuthUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.MyWishService/AuthUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyWishServiceServer).AuthUser(ctx, req.(*AuthUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MyWishService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.MyWishService",
	HandlerType: (*MyWishServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProduct",
			Handler:    _MyWishService_CreateProduct_Handler,
		},
		{
			MethodName: "UpdateProduct",
			Handler:    _MyWishService_UpdateProduct_Handler,
		},
		{
			MethodName: "GetProduct",
			Handler:    _MyWishService_GetProduct_Handler,
		},
		{
			MethodName: "GetProducts",
			Handler:    _MyWishService_GetProducts_Handler,
		},
		{
			MethodName: "BidProduct",
			Handler:    _MyWishService_BidProduct_Handler,
		},
		{
			MethodName: "CreateBidder",
			Handler:    _MyWishService_CreateBidder_Handler,
		},
		{
			MethodName: "GetBidder",
			Handler:    _MyWishService_GetBidder_Handler,
		},
		{
			MethodName: "UpdateBidder",
			Handler:    _MyWishService_UpdateBidder_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _MyWishService_CreateUser_Handler,
		},
		{
			MethodName: "CheckOrCreateUser",
			Handler:    _MyWishService_CheckOrCreateUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _MyWishService_GetUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _MyWishService_DeleteUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _MyWishService_UpdateUser_Handler,
		},
		{
			MethodName: "AuthUser",
			Handler:    _MyWishService_AuthUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/shuoyang2016/mywish/rpc/mywish_service.proto",
}

func init() {
	proto.RegisterFile("github.com/shuoyang2016/mywish/rpc/mywish_service.proto", fileDescriptor1)
}

var fileDescriptor1 = []byte{
	// 1080 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xdd, 0x6e, 0x1b, 0x37,
	0x13, 0xfd, 0x64, 0x7f, 0xb6, 0xa4, 0x91, 0x65, 0x49, 0x94, 0x64, 0xcb, 0xdb, 0xa4, 0x75, 0x79,
	0x11, 0xb8, 0x06, 0xea, 0x4d, 0x1c, 0x20, 0x05, 0x82, 0xf6, 0x22, 0x76, 0x1c, 0x43, 0x40, 0x63,
	0xb7, 0x6b, 0x18, 0x45, 0x73, 0x11, 0x61, 0xb5, 0x4b, 0x48, 0x44, 0x25, 0xed, 0x76, 0xb9, 0x1b,
	0x43, 0xb7, 0x7d, 0x85, 0xbe, 0x4d, 0x5f, 0xa3, 0xaf, 0xd0, 0x8b, 0x3e, 0x46, 0x41, 0x72, 0xe8,
	0xfd, 0x4d, 0xe3, 0xde, 0x69, 0x67, 0x86, 0x67, 0x0e, 0xcf, 0x90, 0x87, 0x82, 0x6f, 0x66, 0x3c,
	0x9e, 0x27, 0xd3, 0x13, 0x2f, 0x58, 0xda, 0x62, 0x9e, 0x04, 0x6b, 0x77, 0x35, 0x3b, 0x7d, 0xfa,
	0xec, 0x85, 0xbd, 0x5c, 0xdf, 0x71, 0x31, 0xb7, 0xa3, 0xd0, 0xc3, 0x9f, 0x13, 0xc1, 0xa2, 0x0f,
	0xdc, 0x63, 0x27, 0x61, 0x14, 0xc4, 0x01, 0xd9, 0x8c, 0x42, 0xcf, 0x7a, 0x34, 0x0b, 0x82, 0xd9,
	0x82, 0xd9, 0x6e, 0xc8, 0x6d, 0x77, 0xb5, 0x0a, 0x62, 0x37, 0xe6, 0xc1, 0x4a, 0xe8, 0x12, 0xeb,
	0xe4, 0x21, 0xd8, 0xc1, 0x8a, 0xad, 0xb1, 0xfe, 0xe9, 0x03, 0xea, 0xc3, 0x28, 0xf0, 0x13, 0x2f,
	0xc6, 0x15, 0xf6, 0x43, 0x56, 0x2c, 0xdc, 0x35, 0x8b, 0xf4, 0x02, 0x7a, 0x0b, 0xbd, 0x4b, 0x16,
	0xff, 0xa0, 0x41, 0x1c, 0xf6, 0x6b, 0xc2, 0x44, 0x4c, 0x1e, 0x03, 0x20, 0xec, 0x84, 0xfb, 0xa3,
	0xda, 0x61, 0xed, 0x68, 0xd3, 0x69, 0x62, 0x64, 0xec, 0x93, 0x2f, 0x61, 0xc7, 0xa4, 0x57, 0xee,
	0x92, 0x8d, 0x36, 0x0e, 0x6b, 0x47, 0x4d, 0xa7, 0x85, 0xb1, 0x2b, 0x77, 0xc9, 0xe8, 0xb7, 0x40,
	0xb2, 0xb0, 0x22, 0x0c, 0x56, 0x82, 0x91, 0x27, 0x50, 0xc7, 0x22, 0x05, 0xda, 0x3a, 0xdd, 0x39,
	0x89, 0x42, 0xef, 0xc4, 0x94, 0x99, 0x24, 0xb5, 0xa1, 0x77, 0xc6, 0xfd, 0x02, 0x29, 0x0b, 0x36,
	0xa7, 0xc8, 0xa6, 0x75, 0xda, 0x50, 0x0b, 0xcf, 0xb8, 0xef, 0xc8, 0x20, 0x7d, 0x01, 0x24, 0xbb,
	0x00, 0xdb, 0x1d, 0xc2, 0x16, 0x8b, 0xa2, 0x20, 0x52, 0x6b, 0x76, 0x4f, 0x41, 0xad, 0xb9, 0x90,
	0x11, 0x47, 0x27, 0x68, 0x07, 0xda, 0x67, 0xc9, 0xfa, 0x3a, 0x31, 0x4d, 0x68, 0x17, 0x76, 0x4d,
	0x40, 0x83, 0xd0, 0xf7, 0x30, 0x38, 0x8f, 0x98, 0x1b, 0xb3, 0x02, 0x9d, 0xaf, 0xa1, 0xb5, 0x62,
	0x77, 0x93, 0x7f, 0xdb, 0x0f, 0xac, 0xd8, 0x1d, 0xfe, 0x26, 0xfb, 0x50, 0x4f, 0x04, 0x8b, 0xa4,
	0x9e, 0x1b, 0x4a, 0xcf, 0x6d, 0xf9, 0x39, 0xf6, 0xe9, 0x5b, 0x18, 0x16, 0xf0, 0x91, 0x3d, 0x85,
	0x6d, 0x11, 0xbb, 0x71, 0x22, 0x2a, 0xe8, 0x63, 0x86, 0x74, 0x61, 0x73, 0x29, 0x66, 0x38, 0x00,
	0xf9, 0x93, 0x3e, 0xcf, 0x0a, 0x2f, 0x1e, 0x36, 0x50, 0xfa, 0x1d, 0xf4, 0x73, 0x8b, 0xfe, 0xe3,
	0xb8, 0xfe, 0xa8, 0xc1, 0xe0, 0x36, 0xf4, 0xcb, 0x1a, 0x7d, 0xe2, 0x1c, 0x3d, 0x81, 0x4e, 0xa4,
	0x2b, 0x27, 0x79, 0x6d, 0xda, 0x18, 0xbe, 0x55, 0x12, 0xc9, 0x39, 0x86, 0x11, 0xf7, 0xd8, 0x68,
	0x53, 0xb1, 0x00, 0x64, 0xc1, 0x3d, 0xe6, 0xe8, 0x04, 0xa1, 0xd0, 0xe6, 0x62, 0xe2, 0x33, 0x77,
	0x31, 0xd1, 0x95, 0xff, 0x3f, 0xac, 0x1d, 0x35, 0x9c, 0x16, 0x17, 0xaf, 0x99, 0xbb, 0x50, 0xa5,
	0x64, 0x08, 0xdb, 0x53, 0xee, 0xcb, 0x26, 0x5b, 0xaa, 0xc9, 0xd6, 0x94, 0xfb, 0x63, 0x9f, 0x5e,
	0xc3, 0xb0, 0xc0, 0x1d, 0x77, 0xff, 0x09, 0xf2, 0xfb, 0x50, 0x57, 0xfd, 0xd2, 0x81, 0xca, 0xcf,
	0xb1, 0x4f, 0x39, 0x8c, 0xce, 0xe7, 0xcc, 0xfb, 0xe5, 0x3a, 0xd2, 0x73, 0x95, 0x9b, 0x30, 0x82,
	0x7c, 0x06, 0x4d, 0xb5, 0x53, 0x75, 0x6d, 0x6a, 0x6a, 0x6a, 0x0d, 0x19, 0x90, 0x77, 0x86, 0x0c,
	0x60, 0x8b, 0x2d, 0x5d, 0xbe, 0xc0, 0x71, 0xea, 0x0f, 0x62, 0x41, 0x23, 0x74, 0x85, 0xb8, 0x0b,
	0x22, 0x5f, 0xed, 0xbf, 0xe9, 0xdc, 0x7f, 0xd3, 0x6b, 0x38, 0xa8, 0x68, 0x85, 0xfc, 0x47, 0x50,
	0x17, 0x89, 0xe7, 0x31, 0xa6, 0xc9, 0x37, 0x1c, 0xf3, 0x29, 0x33, 0x3e, 0x8b, 0x5d, 0xbe, 0x10,
	0xd8, 0xca, 0x7c, 0xd2, 0x1e, 0x74, 0x5e, 0x25, 0xf1, 0x3c, 0x43, 0x99, 0x12, 0xe8, 0xa6, 0x21,
	0xbc, 0x13, 0x7d, 0xe8, 0x69, 0xcd, 0xb2, 0x85, 0x03, 0x20, 0xd9, 0x60, 0x5a, 0xfa, 0x9a, 0x2d,
	0x58, 0xa9, 0x34, 0x1b, 0xc4, 0xd2, 0x2e, 0xec, 0x5e, 0xb2, 0x38, 0x5b, 0xd7, 0x83, 0xce, 0x7d,
	0x24, 0xc5, 0x2b, 0xc9, 0x2a, 0xf1, 0xca, 0x02, 0xd0, 0x1b, 0xe8, 0xeb, 0xe8, 0x19, 0xf7, 0xfd,
	0xdc, 0x0c, 0xa6, 0x2a, 0x90, 0x8e, 0xb5, 0xa1, 0x03, 0x63, 0x9f, 0x7c, 0x01, 0x2d, 0x4c, 0x66,
	0x9c, 0x0d, 0x74, 0x48, 0x19, 0xdb, 0x9e, 0xb1, 0x03, 0x03, 0x8a, 0xcd, 0x6c, 0xe8, 0x5e, 0xb2,
	0xf8, 0xe1, 0x9d, 0xe4, 0x46, 0x32, 0x0b, 0x10, 0x65, 0x08, 0x7d, 0xad, 0x61, 0x0e, 0x48, 0x36,
	0xcd, 0x87, 0x75, 0xf9, 0xf1, 0x57, 0xb0, 0xa5, 0xfc, 0x80, 0xb4, 0xa0, 0x7e, 0x73, 0x7b, 0x7e,
	0x7e, 0x71, 0x73, 0xd3, 0xfd, 0x1f, 0xe9, 0x43, 0xe7, 0xf2, 0xe2, 0xea, 0xc2, 0x19, 0x9f, 0x4f,
	0xde, 0xbc, 0x1a, 0x7f, 0x7f, 0xeb, 0x5c, 0x74, 0x6b, 0xa7, 0x7f, 0x37, 0xa1, 0xfd, 0x76, 0xfd,
	0x13, 0x17, 0xf3, 0x1b, 0xfd, 0x6a, 0x91, 0xf7, 0xd0, 0xce, 0x19, 0x0f, 0x39, 0x50, 0xf7, 0xaa,
	0xca, 0xec, 0x2c, 0xab, 0x2a, 0x85, 0x9c, 0xf7, 0x7e, 0xfb, 0xf3, 0xaf, 0xdf, 0x37, 0xba, 0xb4,
	0x65, 0x7f, 0x78, 0x66, 0x5e, 0xa3, 0x97, 0xb5, 0x63, 0x89, 0x9f, 0xbb, 0x58, 0x88, 0x5f, 0x65,
	0x14, 0x88, 0x5f, 0x79, 0x0f, 0x0d, 0xbe, 0x55, 0xc4, 0x77, 0x00, 0x52, 0xd3, 0x22, 0x7b, 0x0a,
	0xa1, 0xf4, 0x94, 0x59, 0xfb, 0xa5, 0xb8, 0x39, 0x48, 0x0a, 0xb6, 0x4d, 0xb2, 0xb0, 0xe4, 0x1d,
	0xb4, 0x32, 0x46, 0x48, 0x8a, 0x8b, 0x8d, 0x9f, 0x5a, 0xa3, 0x72, 0x02, 0x61, 0x47, 0x0a, 0x96,
	0x90, 0x6e, 0x06, 0xd6, 0x5e, 0x70, 0x11, 0x93, 0x9f, 0x01, 0xd2, 0x37, 0x0a, 0xf9, 0x96, 0x5e,
	0x39, 0xe4, 0x5b, 0x7e, 0xcc, 0xa8, 0xa5, 0x80, 0x07, 0xb4, 0x93, 0x05, 0x9e, 0x72, 0x5f, 0x4a,
	0xf1, 0x0e, 0x76, 0xb2, 0x87, 0x92, 0x8c, 0x32, 0xe3, 0xca, 0x9d, 0x24, 0xeb, 0xa0, 0x22, 0x63,
	0xce, 0x9e, 0x6a, 0xd0, 0xa1, 0x20, 0x1b, 0xe8, 0x63, 0x2a, 0xb1, 0xaf, 0xa0, 0x79, 0x7f, 0x4e,
	0xc9, 0xd0, 0xec, 0x3b, 0x8f, 0xba, 0x57, 0x0c, 0x23, 0x24, 0x51, 0x90, 0x3b, 0x24, 0x03, 0x29,
	0xb9, 0x66, 0xcf, 0x32, 0x72, 0xad, 0x38, 0xf5, 0xd6, 0x41, 0x45, 0x26, 0xcf, 0xd5, 0x2a, 0x70,
	0x75, 0x00, 0x52, 0x1f, 0x40, 0x89, 0x4b, 0x6e, 0x81, 0x12, 0x57, 0x18, 0x06, 0x1e, 0x09, 0xda,
	0x90, 0xa8, 0xd2, 0x96, 0x25, 0x66, 0x08, 0xbd, 0x92, 0xc7, 0x92, 0xc7, 0x1a, 0xe2, 0x23, 0x36,
	0x6f, 0x7d, 0xfe, 0xb1, 0x34, 0x36, 0x7a, 0xa4, 0x1a, 0xed, 0xd1, 0x9e, 0x69, 0x64, 0x47, 0x6c,
	0xc6, 0x45, 0xac, 0x3b, 0xbe, 0x81, 0x3a, 0xba, 0x1e, 0xe9, 0x1b, 0x61, 0xb3, 0xe8, 0x83, 0x7c,
	0xd0, 0xb8, 0xa7, 0xc2, 0x04, 0x72, 0x4f, 0x9e, 0x5c, 0x03, 0xa4, 0x2e, 0x8b, 0x6a, 0x94, 0xbc,
	0x18, 0xd5, 0xa8, 0xb2, 0x63, 0x0d, 0x78, 0x9c, 0x02, 0x3a, 0x00, 0xa9, 0xc3, 0x23, 0x60, 0xe9,
	0x1d, 0x40, 0xc0, 0xaa, 0xa7, 0x40, 0xcb, 0x6b, 0xe5, 0xe4, 0xfd, 0x11, 0x1a, 0xe6, 0x79, 0x21,
	0x7a, 0x63, 0x85, 0x07, 0xc8, 0x1a, 0x16, 0xa2, 0xf9, 0x8b, 0x46, 0xdb, 0xf7, 0x1a, 0xba, 0x49,
	0x3c, 0x7f, 0x59, 0x3b, 0x9e, 0x6e, 0xab, 0x7f, 0xb6, 0xcf, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff,
	0x2c, 0x75, 0xd0, 0x83, 0xca, 0x0b, 0x00, 0x00,
}
